### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by ccguyka** [ccguyka/show-updates-maven-plugin#1]
Test coverage is at 66%. See https://coveralls.io/builds/16924880

Should be close to 100%

**Comment by 0pdd** [comment]
@ccguyka 3 puzzles [#34](https://github.com/ccguyka/show-updates-maven-plugin/issues/34), [#35](https://github.com/ccguyka/show-updates-maven-plugin/issues/35), [#36](https://github.com/ccguyka/show-updates-maven-plugin/issues/36) are still not solved.

**Comment by 0pdd** [comment]
@ccguyka 2 puzzles [#34](https://github.com/ccguyka/show-updates-maven-plugin/issues/34), [#35](https://github.com/ccguyka/show-updates-maven-plugin/issues/35) are still not solved; solved: [#36](https://github.com/ccguyka/show-updates-maven-plugin/issues/36).

**Comment by 0pdd** [comment]
@ccguyka 2 puzzles [#35](https://github.com/ccguyka/show-updates-maven-plugin/issues/35), [#39](https://github.com/ccguyka/show-updates-maven-plugin/issues/39) are still not solved; solved: [#34](https://github.com/ccguyka/show-updates-maven-plugin/issues/34), [#36](https://github.com/ccguyka/show-updates-maven-plugin/issues/36).

**Comment by 0pdd** [comment]
@ccguyka the puzzle [#35](https://github.com/ccguyka/show-updates-maven-plugin/issues/35) is still not solved; solved: [#34](https://github.com/ccguyka/show-updates-maven-plugin/issues/34), [#36](https://github.com/ccguyka/show-updates-maven-plugin/issues/36), [#39](https://github.com/ccguyka/show-updates-maven-plugin/issues/39).

**Comment by 0pdd** [comment]
@ccguyka all 4 puzzles are solved here: [#34](https://github.com/ccguyka/show-updates-maven-plugin/issues/34), [#35](https://github.com/ccguyka/show-updates-maven-plugin/issues/35), [#36](https://github.com/ccguyka/show-updates-maven-plugin/issues/36), [#39](https://github.com/ccguyka/show-updates-maven-plugin/issues/39).
